In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("creditcard.csv")

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

In [5]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  Class  
0  149.62      0  
1    2.69      0  
2  378.66      0  
3  123.50      0  
4   69.99      0

In [6]:
df.shape

(284807, 31)

In [7]:
df["Class"].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [ ]:
284315/492

In [8]:
### Independent and Dependent Features
X=df.drop("Class", axis=1)
y=df.Class

In [9]:
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9       V10       V11       V12       V13       V14  \
0  0.098698  0.363787  0.090794 -0.551600 -0.617801 -0.991390 -0.311169   
1  0.085102 -0.255425 -0.166974  1.612727  1.065235  0.489095 -0.143772   
2  0.247676 -1.514654  0.207643  0.624501  0.066084  0.717293 -0.165946   
3  0.377436 -1.387024 -0.054952 -0.226487  0.178228  0.507757 -0.287924   
4 -0.270533  0.817739  0.753074 -0.822843  0.538196  1.345852 -1.119670   

        V15       V16       V17       V18       V19       V20       V21  \
0  1.468177 -0.470401  0.207971  0.025791  0.403993  0.251412 -0.018307   
1  0.635558  0.463917 -0.114805 -0.183361 -0.145783 -0.069083 -0.225775   
2  2.345865 -2.890083  1.109969 -0.121359 -2.261857  0.524980  0.247998   
3 -0.631418 -1.059647 -0.684093  1.965775 -1.232622 -0.208038 -0.108300   
4  0.175121 -0.451449 -0.237033 -0.038195  0.803487  0.408542 -0.009431   

        V22       V23       V24       V25       V26       V27       V28  \
0  0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1 -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2  0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3  0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4  0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   

   Amount  
0  149.62  
1    2.69  
2  378.66  
3  123.50  
4   69.99

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test=train_test_split(X, y, train_size=0.7)

### Random Forest Classifier

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
model=RandomForestClassifier()

In [15]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [16]:
y_pred=model.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
print(confusion_matrix(y_test, y_pred))

[[85298     5]
 [   23   117]]


In [19]:
print(accuracy_score(y_test, y_pred))

0.9996722961506501


In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85303
           1       0.96      0.84      0.89       140

    accuracy                           1.00     85443
   macro avg       0.98      0.92      0.95     85443
weighted avg       1.00      1.00      1.00     85443



### Logistic Regression classifier

In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [23]:
model1=LogisticRegression()

In [24]:
grid={"C":10.0**np.arange(-2,3), "penalty":["l1","l2"]}
cv=KFold(n_splits=5, random_state=None, shuffle=False)

In [25]:
clf=GridSearchCV(model1, grid, cv=cv, n_jobs=-1, scoring="f1_macro")

In [26]:
clf.fit(X_train, y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [       nan 0.82698291        nan 0.84017895        nan 0.83961734
        nan 0.82944504        nan 0.83626687]
  warnings.warn(
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [27]:
y_pred=clf.predict(X_test)

In [28]:
print(confusion_matrix(y_test, y_pred))

[[85257    46]
 [   39   101]]


In [29]:
print(accuracy_score(y_test, y_pred))

0.9990051847430451


In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85303
           1       0.69      0.72      0.70       140

    accuracy                           1.00     85443
   macro avg       0.84      0.86      0.85     85443
weighted avg       1.00      1.00      1.00     85443



In [31]:
y_train.value_counts()

0    199012
1       352
Name: Class, dtype: int64

#### Under-Sampling: Random under sampling

In [32]:
from collections import Counter
Counter(y_train)

Counter({0: 199012, 1: 352})

In [33]:
from collections import Counter
from imblearn.under_sampling import NearMiss
us=NearMiss(0.8)
X_train_us,y_train_us=us.fit_resample(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [39]:
352/440

0.8

In [35]:
Counter(y_train)
Counter(y_train_us)

Counter({0: 440, 1: 352})

In [40]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(X_train_us,y_train_us)

RandomForestClassifier()

In [41]:
y_pred2=model2.predict(X_test)
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[74523 10780]
 [   12   128]]
0.8736935734934401
              precision    recall  f1-score   support

           0       1.00      0.87      0.93     85303
           1       0.01      0.91      0.02       140

    accuracy                           0.87     85443
   macro avg       0.51      0.89      0.48     85443
weighted avg       1.00      0.87      0.93     85443



#### Tomek: Under sampling

In [45]:
from imblearn.under_sampling import TomekLinks

In [46]:
ust=TomekLinks()

In [49]:
X_ust, y_ust = ust.fit_resample(X_train, y_train)

KeyboardInterrupt: 

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()
model2.fit(X_ust,y_ust)

In [ ]:
y_pred2=model2.predict(X_test)
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

#### Advantages of this approach:

It can help improve the runtime of the model and solve the memory problems by reducing the number of training data samples when the training data set is enormous.

#### Disadvantages:

It can discard useful information about the data itself which could be necessary for building rule-based classifiers such as Random Forests.
The sample chosen by random undersampling may be a biased sample. And it will not be an accurate representation of the population in that case. Therefore, it can cause the classifier to perform poorly on real unseen data.

#### Over Sampling

In [50]:
from imblearn.over_sampling import RandomOverSampler

In [51]:
os=RandomOverSampler(0.75)
X_train_os,y_train_os=os.fit_resample(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [53]:
Counter(y_train)

Counter({0: 199012, 1: 352})

In [54]:
Counter(y_train_os)

Counter({0: 199012, 1: 149259})

In [55]:
from sklearn.ensemble import RandomForestClassifier
model3=RandomForestClassifier()
model3.fit(X_train_os,y_train_os)

RandomForestClassifier()

In [56]:
y_pred3=model3.predict(X_test)
print(confusion_matrix(y_test,y_pred3))
print(accuracy_score(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[85299     4]
 [   23   117]]
0.9996839998595555
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85303
           1       0.97      0.84      0.90       140

    accuracy                           1.00     85443
   macro avg       0.98      0.92      0.95     85443
weighted avg       1.00      1.00      1.00     85443



#### Advantages:

Unlike undersampling, this method leads to no information loss.

#### Disadvantages:

It increases the likelihood of overfitting since it replicates the minority class events.

### SMOTE:
SMOTE (synthetic minority oversampling technique) is one of the most commonly used oversampling methods to solve the imbalance problem.
It aims to balance class distribution by randomly increasing minority class examples by replicating them.
SMOTE synthesises new minority instances between existing minority instances. It generates the virtual training records by linear interpolation for the minority class

In [57]:
from imblearn.over_sampling import SMOTE

In [58]:
ost=SMOTE(0.75)
X_train_ost,y_train_ost=ost.fit_resample(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [60]:
Counter(y_train)

Counter({0: 199012, 1: 352})

In [61]:
Counter(y_train_ost)

Counter({0: 199012, 1: 149259})

In [62]:
from sklearn.ensemble import RandomForestClassifier
model4=RandomForestClassifier()
model4.fit(X_train_ost,y_train_ost)

RandomForestClassifier()

In [63]:
y_pred4=model4.predict(X_test)
print(confusion_matrix(y_test,y_pred4))
print(accuracy_score(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

[[85293    10]
 [   18   122]]
0.9996722961506501
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85303
           1       0.92      0.87      0.90       140

    accuracy                           1.00     85443
   macro avg       0.96      0.94      0.95     85443
weighted avg       1.00      1.00      1.00     85443



#### Advantages -

Alleviates overfitting caused by random oversampling as synthetic examples are generated rather than replication of instances.
No loss of information.
It's simple to implement and interpret.

#### Disadvantages -

While generating synthetic examples, SMOTE does not take into consideration neighboring examples can be from other classes. This can increase the overlapping of classes and can introduce additional noise.
SMOTE is not very practical for high dimensional data.

### SMOTE-Tomek:
A hybrid method which is a mixture of the above two methods, it uses an under-sampling method (Tomek) with an oversampling method (SMOTE). ... Class 0 is downsampled and class 1 is upsampled.

In [64]:
from imblearn.combine import SMOTETomek

In [65]:
ostt=SMOTETomek(0.75)
X_train_ostt,y_train_ostt=os.fit_resample(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


In [67]:
Counter(y_train)

Counter({0: 199012, 1: 352})

In [68]:
Counter(y_train_ostt)

Counter({0: 199012, 1: 149259})

In [69]:
from sklearn.ensemble import RandomForestClassifier
model5=RandomForestClassifier()
model5.fit(X_train_ostt,y_train_ostt)

RandomForestClassifier()

In [70]:
y_pred5=model5.predict(X_test)
print(confusion_matrix(y_test,y_pred5))
print(accuracy_score(y_test,y_pred5))
print(classification_report(y_test,y_pred5))

[[85299     4]
 [   23   117]]
0.9996839998595555
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85303
           1       0.97      0.84      0.90       140

    accuracy                           1.00     85443
   macro avg       0.98      0.92      0.95     85443
weighted avg       1.00      1.00      1.00     85443



##### Following are some approaches that you should consider to deal with imbalanced datasets

1. Use K-fold Cross-Validation in the right way
2. Ensemble different re-sampled datasets
3. Resample with different ratios
4. Cluster the abundant class